title: 29.97fps→25fps逆テレシネ(IVTC)ガイド
# logo: /assets/img/logo.png
description: A guide for IVTC from 29.97fps to 25fps
show_downloads: false
google_analytics: G-8X2CV5ZXJK
theme: jekyll-theme-slate
timezone: Asia/Tokyo
date_format: "%Y-%m-%d"
