title: 29.97fps→25fps逆テレシネ(IVTC)ガイド
# logo: /assets/img/logo.png
description: 29.97fps→25fpsの逆テレシネ(IVTC)ガイド
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
timezone: Asia/Tokyo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: "%Y-%m-%d"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      toc: true
      toc_label: "目次"
      author_profile: true
      show_date: true
      read_time: false
      comments: true
      share: true
      related: true
      permalink: /:categories/:year/:month/:day/:title.html
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
