title: 29.97fps→25fps逆テレシネ(IVTC)ガイド
# logo: /assets/img/logo.png
description: 29.97fps→25fps逆テレシネ(IVTC)ガイド
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
timezone: Asia/Tokyo
date_format: "%Y-%m-%d"
