title: 29.97fps→25fps逆テレシネ(IVTC)ガイド
# logo: /assets/img/logo.png
description: >- # this means to ignore newlines until "baseurl:"
  29.97fps→25fpsの逆テレシネ(IVTC)ガイド
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
timezone: Asia/Tokyo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: "%Y-%m-%d"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ikotas"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      toc: true
      toc_label: "目次"
      author_profile: true
      show_date: true
      read_time: false
      comments: true
      share: true
      related: true
      permalink: /:categories/:year/:month/:day/:title.html
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
